name: Rust
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  actions: read
  checks: write

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  build-and-test:
    name: Build and Test Rust crates (${{ matrix.os }}, ${{ matrix.arch }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            arch: x86
            target: i686-unknown-linux-gnu
          - os: windows-latest
            arch: x64
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            arch: x86
            target: i686-pc-windows-msvc
          - os: macos-latest
            arch: x64
            target: x86_64-apple-darwin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      # https://github.com/actions-rust-lang/setup-rust-toolchain/blob/main/rust.json
      - name: Install Rust Problem Matcher
        if: matrix.os == 'ubuntu-latest'
        run: echo "::add-matcher::.github/rust.json"

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            rust/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-llvm-cov
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'x64'
        run: cargo +stable install cargo-llvm-cov --locked --force

      - name: Install cargo2junit
        run: cargo install cargo2junit --locked --force

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Install 32-bit Linux linker deps
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'x86'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y gcc-multilib libc6-dev-i386

      - name: Bump opt-level
        if: matrix.os == 'ubuntu-latest'
        working-directory: rust
        run: sed -i '/\[profile.dev]/a opt-level=1' Cargo.toml

      - name: Run Clippy
        working-directory: rust
        run: cargo clippy --all --all-features --target ${{ matrix.target }} -- # -D warnings

      - name: Run Format Check
        working-directory: rust
        run: cargo fmt --all --check

      - name: Compile (tests)
        working-directory: rust
        run: cargo test --no-run --locked --target ${{ matrix.target }}

        # It's faster to `test` before `build` ¯\_(ツ)_/¯
      - name: Compile (pdf-analyzer)
        working-directory: rust
        run: cargo build --quiet --target ${{ matrix.target }}

      - name: Run tests and convert to JUnit format (Unix)
        if: runner.os != 'Windows'
        working-directory: rust
        
        run: RUSTC_BOOTSTRAP=1 cargo test --target ${{ matrix.target }} -- -Z unstable-options --format=json --report-time --quiet | tee test-results.json

      - name: Run tests and convert to JUnit format (Windows)
        if: runner.os == 'Windows'
        working-directory: rust
        # report-time option is not currently supported by cargo2junit: https://github.com/johnterickson/cargo2junit/issues/90
        run: |
          $env:RUSTC_BOOTSTRAP=1
          cargo test --target ${{ matrix.target }} -- -Z unstable-options --format=json --report-time --quiet | tee test-results.json

      - name: Convert test output to JUnit format
        working-directory: rust
        # report-time option is not currently supported by cargo2junit: https://github.com/johnterickson/cargo2junit/issues/90
        if: false
        run: cat test-results.json | cargo2junit > test-results.xml

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: false
        with:
          name: Tests report ${{ matrix.os }} # Name of the check run which will be created
          path: rust/test-results.xml # Path to test results
          reporter: java-junit # Format of test results

      - name: Generate coverage report
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'x64'
        working-directory: rust
        run: cargo llvm-cov --lcov --output-path coverage.lcov

      # - name: SonarQube Scan
      #   uses: SonarSource/sonarqube-scan-action@v6
      #   if: matrix.os == 'ubuntu-latest'
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # - name: Install Bencher CLI
      #   uses: bencherdev/bencher@main
      #   if: matrix.os == 'ubuntu-latest'

      # - name: Track base branch benchmarks with Bencher
      #   if: matrix.os == 'ubuntu-latest'
      #   working-directory: rust
      #   run: |
      #     bencher run \
      #     --project trust-pdf \
      #     --token '${{ secrets.BENCHER_TOKEN }}' \
      #     --branch main \
      #     --testbed ubuntu-latest \
      #     --threshold-measure latency \
      #     --threshold-test t_test \
      #     --threshold-max-sample-size 64 \
      #     --threshold-upper-boundary 0.99 \
      #     --thresholds-reset \
      #     --err \
      #     --adapter json \
      #     --github-actions '${{ secrets.GITHUB_TOKEN }}' \
      #     bencher mock
